artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://xraypneumonia.s3.ap-south-1.amazonaws.com/xray_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  #https://xraypneumonia.s3.ap-south-1.amazonaws.com/xray_data.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOr%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEA2mMHqMfGIsJEQVlOmAg4plHc2GshX5L8VyN3zuqiIMkCIH5xiYlHgVjLoIgyzN4GlbePlUniJtAN2kZhlf%2FP3rXVKuQCCHQQABoMNjkxMjU4NTQwNTMzIgx2yHKgmtxyGXS3ITEqwQJ%2FTuPBkBxa2E4Rqs3UKFD9n6v2qlSRz6PndTOS8jhjtGnRHEB62w7%2BPK0vQsQBKN7voMOBEH5YZQSxWlfzzEMftJBqRHWE79DiSCnasM%2B7a3A4H%2B0mMal1wz%2BHlicoJrmmaPHUeNJwb7KyHavyhutxFpMZq0jhRH%2B49SHSMDByvYCOVmqbW1f%2BmRs2MmXNjUWlH7%2BUMstVWVDq8wE5ba0lxB64S6VbIGDVVTAusTyyD%2BApDYvcTD4pA%2BOKsA1sB8o0XW0NFi8ZUAKJ9xkFZkOJ3KUVGA05G4V3rbs3Mlg%2Fp%2F%2FAHh%2BZEQOMHug8jtjoFy2L9YQ8QwLZPrOhBoywQi080O1rRUVdbIV2Y4JiT0P6w9QPihvgLn7Hv%2F63c8n3aKY%2BEq51YB9zoORfGamOUgzqjI7S7BjS1D6OpVR3rcTnsFsw18%2FZpQY6swJOJ5KfRlWLxCHcdT%2B%2Bfw0U%2FAzrgQN169fWxXYCjTutTErtgC9Arj3s48bRNnoyD%2Fdtya%2BRaNHGZpAJxbU0rdmO05fXGqEpvz9m45p1Lh3vJTYTxuqYPSQUupR%2FeDkq4W%2FnLVybuKpyrDfvTT8MmN%2F5z%2FmZYivi6Qb%2B71%2F4ZmQtwGkGjqqcV%2BeL32gi%2BhZSad7CORVblBK3aLbYYT%2BQqIhqZZYjwa8%2Fbe%2F5g7OGoUvkX%2FQfP1C7GfzZL%2BpM%2BpQinAAgd7r58X4y8G53UvWaSWebz7oF9LOyb4IAe0cbAphJCZc2m2UAOiCBZ3rIJnXEvThVRWmapY5SzoT5TLEUsKczgC8yO0lwhsMhz%2BHhdaP%2FTlDqoIkS%2Fkx1occz2GO%2FZbjgzbkaFSdCD%2FWGkyjGTy9Zkz1I&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230718T113143Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA2B4RYIH2527TTM5G%2F20230718%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Signature=0a5d20fefecd1f82437fe6854d9e48349932db5223fb5be686c9005211b10e89


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5