name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

      - name: Build and Push Docker Container
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login registry.heroku.com -u _ --password-stdin
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release to Heroku
        run: |
          docker pull registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker tag registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
